//Incase we don't know the type of variable.
// let a="500";
// let num=Number(a);
// console.log(typeof(num)); //Number
// console.log(num); //500

// let ab="500ac";
// let num1=Number(ab);
// console.log(typeof(num1)); //Number
// console.log(num1); //NaN =>Not a number NaN is a number that is not a legal number.

// let ab=null;
// let num1=Number(ab);
// console.log(typeof(num1)); //Number
// console.log(num1); // null is coverted to number is 0. Need Revision.

// let ab=undefined;
// let num1=Number(ab);
// console.log(typeof(num1)); //Number
// console.log(num1); //NaN =>Not a number NaN is a number that is not a legal number.

// let ab=true;
// let num1=Number(ab);
// console.log(typeof(num1)); //Number
// console.log(num1); //NaN =>Not a number NaN is a number that is not a legal number.

// let ab=0;
// let num1=Boolean(ab);
// console.log(typeof(num1)); //boolean
// console.log(num1); // it will print false. in place of 0 if you Enter positive 1 or negative -1. it will give true;

// let ab="Ajit";
// let num1=Boolean(ab);
// console.log(typeof(num1)); //boolean
// console.log(num1); // true

// let ab="";
// let num1=Boolean(ab);
// console.log(typeof(num1)); //boolean
// console.log(num1); // it will print false. 

//==========String Conversion
// let ab=33;
// let num1=String(ab);
// console.log(typeof(num1)); //string
// console.log(num1); //33


// let ab=true;
// let num1=String(ab);
// console.log(typeof(num1)); //string
// console.log(num1); //true
